# Generated by Django 4.1 on 2023-11-30 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "genres_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=400)),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("genres", models.ManyToManyField(null=True, to="movie_app.genres")),
            ],
        ),
        migrations.CreateModel(
            name="Collections",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("movies", models.ManyToManyField(to="movie_app.movie")),
            ],
        ),
    ]
